# Generated by Django 4.2 on 2026-07-10 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dockets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assigned_labor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LaborProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('working', 'Working')], default='idle', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('last_location_update', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
