# Generated by Django 4.2 on 2026-07-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockets', '0002_issue_assigned_labor_laborprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolved_photo',
            field=models.ImageField(blank=True, null=True, upload_to='issues/resolved/'),
        ),
    ]
